name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run smoke tests
        run: |
          python fetch_bs.py
          python selenium_test.py

      - name: Run tests
        run: |
          pip install pytest
          pytest
        run: |
          python fetch_bs.py
          python selenium_test.py
